license: "CC0-1.0"
license_url: "https://creativecommons.org/publicdomain/zero/1.0/"

kramdown:
  footnote_backlink: "↩"

collections:
  pages:
    output: true
    permalink: /:path/
  tags:
    output: true
    permalink: /emne/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      lang: no
      published: true
  - scope:
      path: ""
      type: tags
    values:
      layout: tag
      lang: no
